name: rust

on:
  push:
    branches:
      - master

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: update /etc/hosts
        run: |
          sudo echo "172.17.0.1 host.docker.internal" | sudo tee -a /etc/hosts
          cat /etc/hosts
      - name: rust version
        run: |
          docker compose -f support/ci/docker-compose.yml run --rm rust rustc --version
       - name: tests
        run: |
          docker compose -f support/ci/docker-compose.yml run --rm rust /usr/local/src/testing/test.sh /usr/local/src/school
