name: rust

on:
  push:
    branches:
      - master

jobs:
  test:
    name: learning Rust
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: info
        run: |
          rustc --version
      - name: tests
        run: |
          cd support/ci
          docker compose run --rm rust /usr/local/src/testing/test.sh /usr/local/src/school
