name: rust

on:
  push:
    branches:
      - master

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: info
        run: |
          pwd
          ls -l
          docker --version
          rustc --version
      - name: inspect
        run: |
          ls -l /usr/local/src
          ls -l /usr/local/src/school
          ls -l /usr/local/src/testing
      - name: tests
        run: |
          cd support/ci
          docker compose run --rm rust /usr/local/src/testing/test.sh /usr/local/src/school
