name: rust

on:
  push:
    branches:
      - master

jobs:
  test:
    name: learning Rust
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: info
        run: |
          rustc --version
      - name: build
        run: |
          docker build support/ci -t rust:alpine
      - name: tests
        run: |
          docker run --rm -v "$(pwd)/school:/usr/local/src/school" -v "$(pwd)/support/testing:/usr/local/src/testing" rust:alpine /usr/local/src/testing/test.sh /usr/local/src/school
