name: rust

on:
  push:
    branches:
      - master

jobs:
  test:
    name: learning Rust
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: info
        run: |
          rustc --version
      - name: inspect
        run: |
          cd support/ci
          docker compose run --rm rust pwd
          docker compose run --rm rust ls -l
          docker compose run --rm rust ls -l /usr/local/src
          docker compose run --rm rust ls -l /usr/local/src/testing
      - name: inspect 2
        run: |
          docker compose -f ./support/ci/docker-compose-2.yml run --rm rust pwd
          docker compose -f ./support/ci/docker-compose-2.yml run --rm rust ls -l
          docker compose -f ./support/ci/docker-compose-2.yml run --rm rust ls -l /usr/local/src
          docker compose -f ./support/ci/docker-compose-2.yml run --rm rust ls -l /usr/local/src/testing
      - name: tests
        run: |
          cd support/ci
          docker compose run --rm rust /usr/local/src/testing/test.sh /usr/local/src/school
